# Generated by Django 3.2.6 on 2021-08-15 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FindMyCar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dealers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealer_number', models.IntegerField()),
                ('dealer_name', models.CharField(max_length=100)),
                ('dealer_address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='vehicle_listings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_live_id', models.IntegerField()),
                ('vin', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('make', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('stock', models.CharField(max_length=20)),
                ('trim', models.CharField(max_length=20)),
                ('amenities', models.TextField()),
                ('miles', models.IntegerField()),
                ('exterior', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('certified', models.IntegerField()),
                ('transmission', models.CharField(max_length=10)),
                ('body_type', models.CharField(max_length=20)),
                ('speeds', models.FloatField()),
                ('doors', models.FloatField()),
                ('cylinders', models.IntegerField()),
                ('engine', models.CharField(max_length=20)),
                ('displacement', models.FloatField()),
                ('zipCode', models.IntegerField()),
                ('phone', models.FloatField()),
                ('imagefile', models.TextField()),
                ('dealer_number', models.IntegerField()),
                ('Distance', models.FloatField()),
            ],
        ),
    ]
