# Generated by Django 3.2.6 on 2021-08-15 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FindMyCar', '0002_dealers_vehicle_listings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zipinfo',
            name='city',
            field=models.CharField(max_length=50),
        ),
    ]
