# Generated by Django 3.2.6 on 2021-08-15 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FindMyCar', '0003_alter_zipinfo_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle_listings',
            old_name='zipCode',
            new_name='zip_code',
        ),
    ]
