# Generated by Django 3.2.6 on 2021-08-15 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FindMyCar', '0004_rename_zipcode_vehicle_listings_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle_listings',
            name='trim',
            field=models.CharField(max_length=50),
        ),
    ]
