# Generated by Django 3.2.6 on 2021-08-15 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FindMyCar', '0007_remove_vehicle_listings_speeds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle_listings',
            name='phone',
        ),
    ]
