# Generated by Django 3.2.6 on 2021-08-15 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FindMyCar', '0009_alter_vehicle_listings_amenities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle_listings',
            name='engine',
            field=models.CharField(max_length=80),
        ),
    ]
