# Generated by Django 3.2.6 on 2021-08-15 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FindMyCar', '0010_alter_vehicle_listings_engine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle_listings',
            name='Distance',
            field=models.FloatField(null=True),
        ),
    ]
