# Generated by Django 3.2.6 on 2021-08-15 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FindMyCar', '0012_alter_vehicle_listings_body_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle_listings',
            name='stock',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
