# Generated by Django 3.2.6 on 2021-08-15 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FindMyCar', '0014_alter_vehicle_listings_transmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle_listings',
            name='cylinders',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vehicle_listings',
            name='displacement',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='vehicle_listings',
            name='doors',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='vehicle_listings',
            name='engine',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
