# Generated by Django 3.2.6 on 2021-08-15 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FindMyCar', '0015_auto_20210816_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle_listings',
            name='imagefile',
            field=models.TextField(null=True),
        ),
    ]
