# Generated by Django 3.2.6 on 2021-08-15 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FindMyCar', '0017_alter_vehicle_listings_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle_listings',
            name='body_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle_listings',
            name='certified',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vehicle_listings',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='vehicle_listings',
            name='exterior',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle_listings',
            name='make',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle_listings',
            name='miles',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vehicle_listings',
            name='model',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle_listings',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='vehicle_listings',
            name='trim',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle_listings',
            name='vehicle_live_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vehicle_listings',
            name='vin',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle_listings',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
