# Generated by Django 3.2.6 on 2021-08-16 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FindMyCar', '0019_alter_dealers_dealer_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealers',
            name='dealer_address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
