# Generated by Django 3.2.6 on 2021-08-16 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FindMyCar', '0020_alter_dealers_dealer_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle_listings',
            name='zip_code',
            field=models.CharField(max_length=10),
        ),
    ]
